#!/bin/sh

# Determines what the root filesystem type is.

FS_TYPE="$(grep ' / ' /proc/mounts | grep -v "^rootfs" | awk '{print $3}')"
if [ -z "${FS_TYPE}" ]; then
    FS_TYPE=Unknown
fi
echo rootfs_type="$FS_TYPE"
