stages:
  - test
  - renovate
  - publish

variables:
  LICENSE_HEADERS_IGNORE_FILES_REGEXP: "./ltmain.sh"
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  DOCKER_VERSION:
    value: "27.3"
    description: "Version of docker to use in pipelines"

  # Renovate required variables
  RENOVATE_PLATFORM: github
  RENOVATE_ENDPOINT: "https://api.github.com"
  RENOVATE_GIT_AUTHOR: "mender-test-bot <mender@northern.tech>"
  RENOVATE_TOKEN: $GITHUB_BOT_TOKEN_REPO_FULL
  RENOVATE_GITHUB_COM_TOKEN: $GITHUB_BOT_TOKEN_REPO_FULL
  RENOVATE_REPOSITORIES: "mendersoftware/$CI_PROJECT_NAME"
  RENOVATE_REQUIRE_CONFIG: "optional"
  RENOVATE_ONBOARDING: "false"
  RENOVATE_GIT_PRIVATE_KEY: $SSH_PRIVATE_KEY
  RENOVATE_CONFIG_FILE: "$CI_PROJECT_DIR/renovate.json5"
  FORCE_RENOVATE_RUN:
    description: "Force a renovate bot run"
    value: "false"
    options:
      - "true"
      - "false"

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-c++.yml'
  - project: "Northern.tech/Mender/mendertesting"
    file: "qa-common/send-results-to-mantra.yml"
    ref: "master"
  - component: gitlab.com/renovate-bot/renovate-runner/renovate.gitlab-ci@main

default:
  tags:
    - k8s
  retry: !reference [.qa-common-default-retry, retry]

# Override rules
renovate:
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $FORCE_RENOVATE_RUN == "true"'
  stage: renovate
  tags:
    - k8s-small

test:no-tests:
  stage: test
  extends: .test:static-template
  script:
    - cmake -D BUILD_TESTS=OFF .
    - make --jobs=$(nproc --all) --keep-going

test:unit:
  stage: test
  image: registry.gitlab.com/northern.tech/mender/mender-test-containers:base-mender-cpp-master
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
  script:
    - cmake -D COVERAGE=ON .
    - make --jobs=$(nproc --all) --keep-going coverage
    # Clean things up for another round of coverage data gathering
    - mv coverage.lcov coverage_base.lcov
    - make clean
    - find . \( -name '*.gcda' -o -name '*.gcno' \) -exec rm '{}' \;
    # Now run key-value DB tests without LMDB (thus testing BlobDB)
    - cmake -D COVERAGE=ON -D MENDER_USE_LMDB=OFF .
    - make key_value_database_test
    - tests/src/common/key_value_database_test
    - make coverage_no_tests
    - mv coverage.lcov coverage_no_lmdb.lcov
    # And combine the coverage data
    - lcov -a 'coverage_*.lcov' -o coverage.lcov --ignore-errors inconsistent
  artifacts:
    expire_in: 2w
    reports:
      junit: reports/*.xml
    paths:
      - coverage.lcov

test:backward-compat:
  stage: test
  # Keep the image aligned with the oldest LTS at mender-dist-packages
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/debian:12
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    - apt update && apt install -yyq ccache g++ git make lcov pkg-config liblmdb++-dev libboost-dev libboost-log-dev libboost-regex-dev libssl-dev libarchive-dev libdbus-1-dev curl dbus cmake
  script:
    - cmake .
    - make --jobs=$(nproc --all) --keep-going

test:dependencies-download:
  stage: test
  image: registry.gitlab.com/northern.tech/mender/mender-test-containers:base-mender-cpp-master
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    # Make sure system libboost and libarchive won't be used
    - apt -yyq remove 'libboost*-dev' libarchive-dev
  script:
    - cmake -D MENDER_DOWNLOAD_BOOST=ON -D MENDER_DOWNLOAD_LIBARCHIVE=ON .
    - make --jobs=$(nproc --all) --keep-going

.test:static-template:
  stage: test
  image: registry.gitlab.com/northern.tech/mender/mender-test-containers:base-mender-cpp-master
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    - export CC=$(which clang)
    - export CXX=$(which clang++)
  script:
    - cmake
      -D CMAKE_BUILD_TYPE=${BUILD_TYPE}
      ${EXTRA_CMAKE_ARGS}
      .
    - make --jobs=$(nproc --all) --keep-going check

test:static:asan:
  variables:
    BUILD_TYPE: ASan
  extends: .test:static-template

test:static:threadsan:
  extends: .test:static-template
  variables:
    BUILD_TYPE: ThreadSan

test:static:undefinedsan:
  extends: .test:static-template
  variables:
    BUILD_TYPE: UndefSan

test:static:release:
  variables:
    BUILD_TYPE: Release
  extends: .test:static-template

test:static:no-dbus:
  variables:
    EXTRA_CMAKE_ARGS: -D MENDER_USE_DBUS=OFF -D MENDER_EMBED_MENDER_AUTH=ON
  extends: .test:static-template

test:modules-artifact-gen:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/ubuntu:22.04
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    - apt update && apt install -yy $(cat support/modules-artifact-gen/tests/deb-requirements.txt)
    - apt install -yy jq
    # mender-artifact
    - curl -fsSL https://downloads.mender.io/repos/debian/gpg | tee /etc/apt/trusted.gpg.d/mender.asc
    - echo "deb [arch=$(dpkg --print-architecture)] https://downloads.mender.io/repos/workstation-tools ubuntu/jammy/stable main" | tee /etc/apt/sources.list.d/mender.list
    - apt update && apt install -yy mender-artifact
    # Test dependencies
    - pip install -r support/modules-artifact-gen/tests/requirements.txt
  script:
    - python3 -m pytest --verbose --junitxml=results.xml support/modules-artifact-gen/tests
  after_script:
    - export MANTRA_PROJECT_NAME="client_general"
    - !reference [.mantra-push-results]

test:docker:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}
  needs: []
  tags:
    - hetzner-amd-beefy
  services:
    - name: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:${DOCKER_VERSION}-dind
      alias: docker
  stage: test
  script:
    - ./tests/build-docker

publish:tests:
  stage: publish
  allow_failure: true
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/python:3.11
  dependencies:
    - test:unit
  before_script:
    - !reference [.qa-common-network-apt-retry, before_script]
    # Install dependencies
    - apt update && apt install -yyq lcov
    - pip install cpp-coveralls pyyaml

    # eddyxu/cpp-coveralls appears dead, but there doesn't seem to be an
    # alternative. Use this patch from someone who attempted to fix it. An
    # alternative to this is to use pyyaml<6, but it's better to use just one
    # old component than two.
    - curl -f https://github.com/eddyxu/cpp-coveralls/commit/067c837c04e039e8c70aa53bceda1cded6751408.patch | patch -f /usr/local/lib/python3.11/site-packages/cpp_coveralls/__init__.py

    # Set "TRAVIS_*" variables based on GitLab ones
    - export TRAVIS_BRANCH=$CI_COMMIT_BRANCH
    - export TRAVIS_JOB_ID=$CI_PIPELINE_ID

  script:
    - 'echo "service_name: gitlab-ci" > .coveralls.yml'
    - cpp-coveralls
      --repo-token ${COVERALLS_TOKEN}
      --no-gcov
      --lcov-file coverage.lcov

publish:tests:codecov:
  stage: publish
  image: alpine
  before_script:
    - apk add --no-cache bash curl findutils git
  dependencies:
    - test:unit
  script:
    - curl -s https://codecov.io/bash | bash -s -- -Z
