
comment:
  # We have one publish:tests job, so all data is reported to codecov
  # in one report. We should add a comment in the PR immediately.
  after_n_builds: 1

codecov:
  notify:
  # We have one publish:tests job, so all data is reported to codecov
  # in one report. We should update the codecov status (meaning whether code
  # coverage requirements for merging the PR are satisfied) in the PR immediately.
    after_n_builds: 1

ignore:
  - "vendor/"
