
comment:
  after_n_builds: 8

codecov:
  notify:
    after_n_builds: 8

coverage:
  status:
    project:
      acceptance:
        flags:
          - acceptance
      unit:
        flags:
          - unit
