codecov:
 notify:
    after_n_builds: 2

comment:
  after_n_builds: 4

coverage:
  status:
    project:
      acceptance:
        after_n_builds: 4
        flags:
          - acceptance
      unit:
        after_n_builds: 1
        flags:
          - unit
