
comment:
  after_n_builds: 5

coverage:
  status:
    project:
      after_n_builds: 3
      acceptance:
        after_n_builds: 4
        flags:
          - acceptance
      unit:
        after_n_builds: 1
        flags:
          - unit
