codecov:
 notify:
    after_n_builds: 10

comment:
  after_n_builds: 10

coverage:
  status:
    project:
      acceptance:
        flags:
          - acceptance
      unit:
        flags:
          - unit
