
comment:
  # We have one publish:tests job, so all data is reported to codecov
  # in one report. We should crate a comment in the PR immediately.
  after_n_builds: 1

codecov:
  notify:
  # We have one publish:tests job, so all data is reported to codecov
  # in one report. We should update the codecov status in the PR immediately.
    after_n_builds: 1

coverage:
  status:
    project:
      unit:
        flags:
          - unit

ignore:
  - "vendor/"
