#!/bin/sh

set -e

STATE="$1"
FILES="$2"

case "$STATE" in
    ArtifactInstall)
        RPMS=
        DEBS=
        for file in "$FILES"/files/*; do
            case "$file" in
                *.rpm)
                    RPMS="$RPMS $file"
                    ;;
                *.deb)
                    DEBS="$DEBS $file"
                    ;;
            esac
        done
        [ -n "$RPMS" ] && rpm -U $RPMS
        [ -n "$DEBS" ] && dpkg -i $DEBS
        ;;
esac
exit 0
