#!/bin/sh

set -e

STATE="$1"
FILES="$2"

case "${STATE}" in
    ArtifactInstall)
        for file in "${FILES}"/files/*; do
            chmod u+x "${file}"
            "${file}"
        done
        ;;
esac
exit 0
