#!/bin/sh

set -e

STATE="$1"
FILES="$2"

tmp_dest_dir="$FILES"/tmp/dest_dir
dest_dir_file="$FILES"/files/dest_dir
filename_file="$FILES"/files/filename
permissions_file="$FILES"/files/permissions

case "$STATE" in

    NeedsArtifactReboot)
        echo "No"
    ;;

    SupportsRollback)
        echo "Yes"
    ;;

    ArtifactInstall)
        dest_dir=$(cat $dest_dir_file)
        filename=$(cat $filename_file)
        test -z "$dest_dir" -o -z "$filename" && \
            echo "Fatal error: dest_dir or filename are undefined." && exit 1
        mkdir -p $dest_dir
        mkdir -p $tmp_dest_dir
        if test -f ${dest_dir}/${filename}
        then
            if ! cp -a ${dest_dir}/${filename} ${tmp_dest_dir}
            then
                ret=$?
                # Make sure there is no half-backup lying around.
                rm -rf ${tmp_dest_dir}
                exit $ret
            fi
        fi
        cp "$FILES"/files/$filename ${dest_dir}/${filename}
        # Previous revisions of this update module did not use the
        # permissions_file, so it might not exist.
        if test -f $permissions_file
        then
            chmod $(cat $permissions_file) ${dest_dir}/${filename}
        fi
        ;;

    ArtifactRollback)
        filename=$(cat $filename_file)
        test -f $tmp_dest_dir/$filename || exit 0
        dest_dir=$(cat $dest_dir_file)
        test -z "$dest_dir" -o -z "$filename" && \
            echo "Fatal error: dest_dir or filename are undefined." && exit 1
        rm ${dest_dir}/${filename}
        cp -a $tmp_dest_dir/$filename ${dest_dir}/${filename}
        ;;
esac

exit 0

